
empathetic_response:
  class: src.config.EvalTaskCfg
  args:
    evaluator: emo_llm
    summarizer: AvgThreshold

aed_instruct:
  class: src.config.EvalTaskCfg
  args:
    evaluator: aed_llm
    summarizer: AvgThreshold

multiturn_fluency:
  class: src.config.EvalTaskCfg
  args:
    evaluator: multiturn_fluency_llm
    summarizer: AvgThreshold

dialect_response:
  class: src.config.EvalTaskCfg
  args:
    evaluator: dialect_llm
    summarizer: AvgThreshold

human_morality:
  class: src.config.EvalTaskCfg
  args:
    evaluator: acceptance_llm
    summarizer: AvgThreshold

human_likeness:
  class: src.config.EvalTaskCfg
  args:
    evaluator: human_likeness_llm
    summarizer: AvgThreshold

care_nsv:
  class: src.config.EvalTaskCfg
  args:
    evaluator: nsv_care_llm
    summarizer: AvgThreshold

care_age:
  class: src.config.EvalTaskCfg
  args:
    evaluator: age_care_llm
    summarizer: AvgThreshold

humandial_task1:
  class: src.config.EvalTaskCfg
  args:
    evaluator: humandial_task1_llm
    summarizer: AvgHumanDialChallenge
    batch_size: 150

humandial_task2:
  class: src.config.EvalTaskCfg
  args:
    evaluator: humandial_task2_llm
    summarizer: AvgHumanDialChallenge
    batch_size: 150

humandial_task3:
  class: src.config.EvalTaskCfg
  args:
    evaluator: humandial_task3_llm_offline
    summarizer: AvgHumanDialChallenge
    batch_size: 150